import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import NavBar from "@/app/components/nav/NavBar";
import Footer from "@/app/components/footer/Footer";
import './globals.css'
import CartProvider from "@/app/providers/CartProvider";
import {Toaster} from "react-hot-toast";

const poppins = Poppins({ subsets: ['latin'],weight:["400","700"] })

export const metadata: Metadata = {
  title: 'shopping center',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={"${poppins.className} text-slate-700"}>
        <Toaster toastOptions={{
          style:{
            background: "rgb(51 65 85)",
            color:"#fff",
          }
        }}/>
        <CartProvider>
          <div className="flex flex-col min-h-screen">
            <NavBar/>
            <main className="flex-grow ">{children}</main>
            <Footer/>
          </div>
        </CartProvider>
      </body>
    </html>
  )
}
